// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Category struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"created_at"`
}

type Tag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type TimeEntry struct {
	ID          int64         `json:"id"`
	Description string        `json:"description"`
	StartTime   time.Time     `json:"start_time"`
	EndTime     sql.NullTime  `json:"end_time"`
	CreatedAt   time.Time     `json:"created_at"`
	CategoryID  sql.NullInt64 `json:"category_id"`
}

type TimeEntryTag struct {
	TimeEntryID int64 `json:"time_entry_id"`
	TagID       int64 `json:"tag_id"`
}
