// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type TimeEntry struct {
	ID          int64        `json:"id"`
	Description string       `json:"description"`
	StartTime   time.Time    `json:"start_time"`
	EndTime     sql.NullTime `json:"end_time"`
	CreatedAt   time.Time    `json:"created_at"`
}
