// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createTimeEntry = `-- name: CreateTimeEntry :one
INSERT INTO time_entries (
    description,
    start_time
) VALUES (
    ?, ?
)
RETURNING id, description, start_time, end_time, created_at
`

type CreateTimeEntryParams struct {
	Description string    `json:"description"`
	StartTime   time.Time `json:"start_time"`
}

func (q *Queries) CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRowContext(ctx, createTimeEntry, arg.Description, arg.StartTime)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveTimeEntry = `-- name: GetActiveTimeEntry :one
SELECT id, description, start_time, end_time, created_at FROM time_entries
WHERE end_time IS NULL
ORDER BY start_time DESC
LIMIT 1
`

func (q *Queries) GetActiveTimeEntry(ctx context.Context) (TimeEntry, error) {
	row := q.db.QueryRowContext(ctx, getActiveTimeEntry)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const listTimeEntries = `-- name: ListTimeEntries :many
SELECT id, description, start_time, end_time, created_at FROM time_entries
ORDER BY start_time DESC
LIMIT 50
`

func (q *Queries) ListTimeEntries(ctx context.Context) ([]TimeEntry, error) {
	rows, err := q.db.QueryContext(ctx, listTimeEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeEntry
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimeEntry = `-- name: UpdateTimeEntry :one
UPDATE time_entries
SET end_time = ?
WHERE id = ?
RETURNING id, description, start_time, end_time, created_at
`

type UpdateTimeEntryParams struct {
	EndTime sql.NullTime `json:"end_time"`
	ID      int64        `json:"id"`
}

func (q *Queries) UpdateTimeEntry(ctx context.Context, arg UpdateTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRowContext(ctx, updateTimeEntry, arg.EndTime, arg.ID)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}
