// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name)
VALUES (?)
ON CONFLICT(name) DO UPDATE SET name=name
RETURNING id, name
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createTimeEntry = `-- name: CreateTimeEntry :one
INSERT INTO time_entries (
    description,
    start_time
) VALUES (
    ?, ?
)
RETURNING id, description, start_time, end_time, created_at
`

type CreateTimeEntryParams struct {
	Description string    `json:"description"`
	StartTime   time.Time `json:"start_time"`
}

func (q *Queries) CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRowContext(ctx, createTimeEntry, arg.Description, arg.StartTime)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const createTimeEntryTag = `-- name: CreateTimeEntryTag :exec
INSERT INTO time_entry_tags (time_entry_id, tag_id)
VALUES (?, ?)
`

type CreateTimeEntryTagParams struct {
	TimeEntryID int64 `json:"time_entry_id"`
	TagID       int64 `json:"tag_id"`
}

func (q *Queries) CreateTimeEntryTag(ctx context.Context, arg CreateTimeEntryTagParams) error {
	_, err := q.db.ExecContext(ctx, createTimeEntryTag, arg.TimeEntryID, arg.TagID)
	return err
}

const deleteOrphanedTags = `-- name: DeleteOrphanedTags :exec
DELETE FROM tags
WHERE NOT EXISTS (
    SELECT 1 FROM time_entry_tags WHERE tag_id = tags.id
)
`

func (q *Queries) DeleteOrphanedTags(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanedTags)
	return err
}

const deleteTimeEntry = `-- name: DeleteTimeEntry :exec
DELETE FROM time_entries
WHERE id = ?
`

func (q *Queries) DeleteTimeEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTimeEntry, id)
	return err
}

const deleteTimeEntryTags = `-- name: DeleteTimeEntryTags :exec
DELETE FROM time_entry_tags
WHERE time_entry_id = ?
`

func (q *Queries) DeleteTimeEntryTags(ctx context.Context, timeEntryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTimeEntryTags, timeEntryID)
	return err
}

const getActiveTimeEntry = `-- name: GetActiveTimeEntry :one
SELECT id, description, start_time, end_time, created_at FROM time_entries
WHERE end_time IS NULL
ORDER BY start_time DESC
LIMIT 1
`

func (q *Queries) GetActiveTimeEntry(ctx context.Context) (TimeEntry, error) {
	row := q.db.QueryRowContext(ctx, getActiveTimeEntry)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name FROM tags
WHERE name = ?
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTimeEntry = `-- name: GetTimeEntry :one
SELECT id, description, start_time, end_time, created_at FROM time_entries
WHERE id = ?
`

func (q *Queries) GetTimeEntry(ctx context.Context, id int64) (TimeEntry, error) {
	row := q.db.QueryRowContext(ctx, getTimeEntry, id)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name FROM tags
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForTimeEntry = `-- name: ListTagsForTimeEntry :many
SELECT t.id, t.name FROM tags t
JOIN time_entry_tags tet ON t.id = tet.tag_id
WHERE tet.time_entry_id = ?
`

func (q *Queries) ListTagsForTimeEntry(ctx context.Context, timeEntryID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForTimeEntry, timeEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeEntries = `-- name: ListTimeEntries :many
SELECT id, description, start_time, end_time, created_at FROM time_entries
ORDER BY start_time DESC
LIMIT 50
`

func (q *Queries) ListTimeEntries(ctx context.Context) ([]TimeEntry, error) {
	rows, err := q.db.QueryContext(ctx, listTimeEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeEntry
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimeEntry = `-- name: UpdateTimeEntry :one
UPDATE time_entries
SET end_time = ?
WHERE id = ?
RETURNING id, description, start_time, end_time, created_at
`

type UpdateTimeEntryParams struct {
	EndTime sql.NullTime `json:"end_time"`
	ID      int64        `json:"id"`
}

func (q *Queries) UpdateTimeEntry(ctx context.Context, arg UpdateTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRowContext(ctx, updateTimeEntry, arg.EndTime, arg.ID)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const updateTimeEntryFull = `-- name: UpdateTimeEntryFull :one
UPDATE time_entries
SET description = ?, start_time = ?, end_time = ?
WHERE id = ?
RETURNING id, description, start_time, end_time, created_at
`

type UpdateTimeEntryFullParams struct {
	Description string       `json:"description"`
	StartTime   time.Time    `json:"start_time"`
	EndTime     sql.NullTime `json:"end_time"`
	ID          int64        `json:"id"`
}

func (q *Queries) UpdateTimeEntryFull(ctx context.Context, arg UpdateTimeEntryFullParams) (TimeEntry, error) {
	row := q.db.QueryRowContext(ctx, updateTimeEntryFull,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.ID,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}
