// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, color)
VALUES (?, ?)
RETURNING id, name, color, created_at
`

type CreateCategoryParams struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.Color)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name)
VALUES (?)
ON CONFLICT(name) DO UPDATE SET name=name
RETURNING id, name
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createTimeEntry = `-- name: CreateTimeEntry :one
INSERT INTO time_entries (
    description,
    start_time,
    category_id
) VALUES (
    ?, ?, ?
)
RETURNING id, description, start_time, end_time, created_at, category_id
`

type CreateTimeEntryParams struct {
	Description string        `json:"description"`
	StartTime   time.Time     `json:"start_time"`
	CategoryID  sql.NullInt64 `json:"category_id"`
}

func (q *Queries) CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRowContext(ctx, createTimeEntry, arg.Description, arg.StartTime, arg.CategoryID)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}

const createTimeEntryTag = `-- name: CreateTimeEntryTag :exec
INSERT INTO time_entry_tags (time_entry_id, tag_id)
VALUES (?, ?)
`

type CreateTimeEntryTagParams struct {
	TimeEntryID int64 `json:"time_entry_id"`
	TagID       int64 `json:"tag_id"`
}

func (q *Queries) CreateTimeEntryTag(ctx context.Context, arg CreateTimeEntryTagParams) error {
	_, err := q.db.ExecContext(ctx, createTimeEntryTag, arg.TimeEntryID, arg.TagID)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteOrphanedTags = `-- name: DeleteOrphanedTags :exec
DELETE FROM tags
WHERE NOT EXISTS (
    SELECT 1 FROM time_entry_tags WHERE tag_id = tags.id
)
`

func (q *Queries) DeleteOrphanedTags(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanedTags)
	return err
}

const deleteTimeEntry = `-- name: DeleteTimeEntry :exec
DELETE FROM time_entries
WHERE id = ?
`

func (q *Queries) DeleteTimeEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTimeEntry, id)
	return err
}

const deleteTimeEntryTags = `-- name: DeleteTimeEntryTags :exec
DELETE FROM time_entry_tags
WHERE time_entry_id = ?
`

func (q *Queries) DeleteTimeEntryTags(ctx context.Context, timeEntryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTimeEntryTags, timeEntryID)
	return err
}

const getActiveTimeEntry = `-- name: GetActiveTimeEntry :one
SELECT te.id, te.description, te.start_time, te.end_time, te.created_at, te.category_id, c.name as category_name, c.color as category_color 
FROM time_entries te
LEFT JOIN categories c ON te.category_id = c.id
WHERE te.end_time IS NULL
ORDER BY te.start_time DESC
LIMIT 1
`

type GetActiveTimeEntryRow struct {
	ID            int64          `json:"id"`
	Description   string         `json:"description"`
	StartTime     time.Time      `json:"start_time"`
	EndTime       sql.NullTime   `json:"end_time"`
	CreatedAt     time.Time      `json:"created_at"`
	CategoryID    sql.NullInt64  `json:"category_id"`
	CategoryName  sql.NullString `json:"category_name"`
	CategoryColor sql.NullString `json:"category_color"`
}

func (q *Queries) GetActiveTimeEntry(ctx context.Context) (GetActiveTimeEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveTimeEntry)
	var i GetActiveTimeEntryRow
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategoryColor,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, color, created_at FROM categories
WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name FROM tags
WHERE name = ?
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTimeEntry = `-- name: GetTimeEntry :one
SELECT te.id, te.description, te.start_time, te.end_time, te.created_at, te.category_id, c.name as category_name, c.color as category_color 
FROM time_entries te
LEFT JOIN categories c ON te.category_id = c.id
WHERE te.id = ?
`

type GetTimeEntryRow struct {
	ID            int64          `json:"id"`
	Description   string         `json:"description"`
	StartTime     time.Time      `json:"start_time"`
	EndTime       sql.NullTime   `json:"end_time"`
	CreatedAt     time.Time      `json:"created_at"`
	CategoryID    sql.NullInt64  `json:"category_id"`
	CategoryName  sql.NullString `json:"category_name"`
	CategoryColor sql.NullString `json:"category_color"`
}

func (q *Queries) GetTimeEntry(ctx context.Context, id int64) (GetTimeEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getTimeEntry, id)
	var i GetTimeEntryRow
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategoryColor,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, color, created_at FROM categories
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name FROM tags
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForTimeEntry = `-- name: ListTagsForTimeEntry :many
SELECT t.id, t.name FROM tags t
JOIN time_entry_tags tet ON t.id = tet.tag_id
WHERE tet.time_entry_id = ?
`

func (q *Queries) ListTagsForTimeEntry(ctx context.Context, timeEntryID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForTimeEntry, timeEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeEntries = `-- name: ListTimeEntries :many
SELECT te.id, te.description, te.start_time, te.end_time, te.created_at, te.category_id, c.name as category_name, c.color as category_color 
FROM time_entries te
LEFT JOIN categories c ON te.category_id = c.id
WHERE te.end_time IS NOT NULL
ORDER BY te.start_time DESC
LIMIT 50
`

type ListTimeEntriesRow struct {
	ID            int64          `json:"id"`
	Description   string         `json:"description"`
	StartTime     time.Time      `json:"start_time"`
	EndTime       sql.NullTime   `json:"end_time"`
	CreatedAt     time.Time      `json:"created_at"`
	CategoryID    sql.NullInt64  `json:"category_id"`
	CategoryName  sql.NullString `json:"category_name"`
	CategoryColor sql.NullString `json:"category_color"`
}

func (q *Queries) ListTimeEntries(ctx context.Context) ([]ListTimeEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTimeEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimeEntriesRow
	for rows.Next() {
		var i ListTimeEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeEntriesReport = `-- name: ListTimeEntriesReport :many
SELECT te.id, te.description, te.start_time, te.end_time, te.created_at, te.category_id, c.name as category_name, c.color as category_color 
FROM time_entries te
LEFT JOIN categories c ON te.category_id = c.id
WHERE te.end_time IS NOT NULL
AND te.start_time >= ?
AND te.start_time <= ?
AND (
    (?3 = 0)
    OR (te.category_id = ?3)
    OR (?3 = -1 AND te.category_id IS NULL)
)
ORDER BY te.start_time DESC
`

type ListTimeEntriesReportParams struct {
	StartTime      time.Time   `json:"start_time"`
	StartTime_2    time.Time   `json:"start_time_2"`
	CategoryFilter interface{} `json:"category_filter"`
}

type ListTimeEntriesReportRow struct {
	ID            int64          `json:"id"`
	Description   string         `json:"description"`
	StartTime     time.Time      `json:"start_time"`
	EndTime       sql.NullTime   `json:"end_time"`
	CreatedAt     time.Time      `json:"created_at"`
	CategoryID    sql.NullInt64  `json:"category_id"`
	CategoryName  sql.NullString `json:"category_name"`
	CategoryColor sql.NullString `json:"category_color"`
}

func (q *Queries) ListTimeEntriesReport(ctx context.Context, arg ListTimeEntriesReportParams) ([]ListTimeEntriesReportRow, error) {
	rows, err := q.db.QueryContext(ctx, listTimeEntriesReport, arg.StartTime, arg.StartTime_2, arg.CategoryFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimeEntriesReportRow
	for rows.Next() {
		var i ListTimeEntriesReportRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = ?, color = ?
WHERE id = ?
RETURNING id, name, color, created_at
`

type UpdateCategoryParams struct {
	Name  string `json:"name"`
	Color string `json:"color"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory, arg.Name, arg.Color, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const updateTimeEntry = `-- name: UpdateTimeEntry :one
UPDATE time_entries
SET end_time = ?
WHERE id = ?
RETURNING id, description, start_time, end_time, created_at, category_id
`

type UpdateTimeEntryParams struct {
	EndTime sql.NullTime `json:"end_time"`
	ID      int64        `json:"id"`
}

func (q *Queries) UpdateTimeEntry(ctx context.Context, arg UpdateTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRowContext(ctx, updateTimeEntry, arg.EndTime, arg.ID)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}

const updateTimeEntryFull = `-- name: UpdateTimeEntryFull :one
UPDATE time_entries
SET description = ?, start_time = ?, end_time = ?, category_id = ?
WHERE id = ?
RETURNING id, description, start_time, end_time, created_at, category_id
`

type UpdateTimeEntryFullParams struct {
	Description string        `json:"description"`
	StartTime   time.Time     `json:"start_time"`
	EndTime     sql.NullTime  `json:"end_time"`
	CategoryID  sql.NullInt64 `json:"category_id"`
	ID          int64         `json:"id"`
}

func (q *Queries) UpdateTimeEntryFull(ctx context.Context, arg UpdateTimeEntryFullParams) (TimeEntry, error) {
	row := q.db.QueryRowContext(ctx, updateTimeEntryFull,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.CategoryID,
		arg.ID,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.CategoryID,
	)
	return i, err
}
